### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by weitongdao** [cxa/ob-C-stdin#1]
Can we do like this?
###
#+name: who
line1 -> world
line2 ->good
line3 -> <empty line>
line4 -> <empty line>
line5 -> job line

#+begin_src C :stdin who :results output
#include <stdio.h>

int main(int argc, char *argv[]) {
  printf("hello, ");
  char c;
  while ((c=getchar()) != EOF) putchar(c);
  return 0;
}
#+end_src

#+RESULTS:
: hello, world

**Comment by cxa** [comment]
你是想实现什么样的效果？

**Comment by weitongdao** [comment]
一起期待这样的功能，非常感谢您的工作。
就是多行但不连续，输入这样能输入吗？好像有空行了就断了。
### org-babel demo cpp

#+name: 2024-11-05-22-39-50
input1 line1
input2 line2

input3 line3 **->因为上行空行，这行无法被读取**

#+HEADER: :stdin 2024-11-05-22-39-50 :var mystring="" :var myint=0 :var mydouble=0.0
#+BEGIN_SRC C++ :session :exports both :results raw drawer :includes '(<iostream> <stdio.h>)
using namespace std;

cin.getline(  );
cin.getline(  );

cin.getline(  );
cin.getline(  );

#+END_SRC

**Comment by cxa** [comment]
那应该使用这样的格式将包含空行的内容包裹起来：

```
#+name: 2024-11-05-22-39-50
#+begin_example
input1 line1
input2 line2

input3 line3
#+end_example
```
